services:
  postgres:
    image: postgres:16-alpine
    container_name: vixrad-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vixrad
    ports:
      - "5432:5432"
    volumes:
      - vixrad_postgres_data:/var/lib/postgresql/data

volumes:
  vixrad_postgres_data:
